spring:
  zipkin:
    base-url: http://consulti.convini.ec:9411/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-18-228-97-0.sa-east-1.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
  renewalPercentThreshold: 0.85
